
var glossary = [{'term':'Adware','definition':'Software que se apoya en anuncios como parte del propio programa. La publicidad generada es mostrada después de la instalación de dicho programa.'},
{'term':'Amenaza','definition':'Circunstancia que tiene el potencial de causar daños o pérdidas puede ser  en forma de robo, destrucción, divulgación, modificación de datos o negación de servicio (DOS).'},
{'term':'Antispam','definition':'Aplicación o herramienta informática que se encarga de detectar y eliminar correo no deseado.'},
{'term':'Antivirus','definition':'Software utilizado para eliminar programas elaborados con intención destructiva.'},
{'term':'Aplicación engañosa','definition':'Las aplicaciones engañosas pueden introducirse sigilosamente en su equipo cuando navega por la Web. Una vez instaladas, los estafadores las utilizan para cometer fraudes y robos de identidad.'},
{'term':'Autenticación básica','definition':'Esquema de autenticación basado en la web más simple que funciona mediante el envío del nombre de usuario y contraseña con cada solicitud.'},
{'term':'Ataque Web','definition':'Es un ataque que se comete contra una aplicación cliente y se origina desde un lugar en la Web, ya sea desde sitios legítimos atacados o sitios maliciosos que han sido creados para atacar intencionalmente a los usuarios de ésta.'},
{'term':'Ataque Dirigido','definition':'Son aquellos ataques realizados normalmente de manera silenciosa e imperceptible, cuyo objetivo es una persona, empresa o grupos de ambas'},
{'term':'Armouring','definition':'Es una técnica que utilizan los virus para esconderse e impedir ser detectados por los antivirus.'},
{'term':'Blacklist ( Lista negra)','definition':'Es un proceso de identificación y bloqueo de programas, correos electrónicos, direcciones o dominios IP conocidos maliciosos o malévolos.'},
{'term':'Bots (Red)','definition':'Son grupos de ordenadores infectados controlados de forma remota por un hacker.'},
{'term':'Bulo','definition':'Mensaje de correo electrónico con contenido falso o engañoso pero con contenido de alto impacto.'},
{'term':'Caballo de Troya','definition':'Son un tipo de código malicioso que parece ser algo que no es. Permiten hacerse con el control de los ordenadores ajenos sin permiso de los usuarios. Una distinción muy importante entre troyanos y virus reales es que los troyanos no infectan otros archivos y no se propagan automáticamente.'},
{'term':'Carga destructiva','definition':'Una carga destructiva es la actividad maliciosa que realiza el malware. Una carga destructiva es independiente de las acciones de instalación y propagación que realiza el malware.'},
{'term':'Cracker','definition':'Personas que rompen algún sistema de seguridad, ( Fines de lucro, protesta o desafío)'},
{'term':'Crimeware','definition':'Software malicioso como los virus, troyanos, spyware y más.'},
{'term':'Ciberseguridad','definition':'Condición caracterizada por un mínimo de riesgos y amenazas a las infraestructura tecnológicas, los componentes lógicos de la información y las interacciones en el ciberespacio.'},
{'term':'Cibercrimen','definition':'Actos delincuenciales en el ciberespacio  donde el principal objetivo es cometer ilícitos contra individuos, organizaciones y empresas.'},
{'term':'Ciberdelito','definition':'Operaciones ilícitas realizadas por medio de Internet o que tienen como objetivo destruir y dañar ordenadores, medios electrónicos y redes de Internet.'},
{'term':'Cifrado','definition':'Proceso de codificación de información sensible para poder evitar que esta llegue a personas no autorizadas.'},
{'term':'Control de acceso a la red (Nac)','definition':'Su principal objetivo es asegurar que todos los dispositivos que sean conectados  a las redes corporativas, cumplan con las políticas de seguridad establecidas para evitar amenazas.'},
{'term':'Correo no deseado','definition':'cualquier comunicación que nos llega por cualquier medio no habiendo sido solicitada y que no era esperada por el usuario que la recibe.'},
{'term':'Cookie','definition':'Archivos que se guardan en los equipos para que los sitios web recuerden determinados datos.'},
{'term':'Definición de virus','definition':'Procedimiento por medio del cual el antivirus actualiza su base de datos de definiciones de virus. Los archivos de definición tienen protección contra todos los virus, gusanos, troyanos y otros riesgos de seguridad más recientes'},
{'term':'Delito Informático','definition':'Comportamientos ilícitos que se llevan a cabo mediante herramientas electrónicas para atacar contra la seguridad de los datos informáticos.'},
{'term':'Desbordamiento del búfer','definition':'Se producen cuando un programa sobrescribe otras partes de la memoria del equipo para almacenar más datos de los permitidos, provocando errores o bloqueos.'},
{'term':'Driver','definition':'Es un programa, conocido como controlador, que permite la gestión de los dispositivos conectados al ordenador (generalmente, periféricos como impresoras, unidades de CD-ROM, etc).'},
{'term':'Dropper','definition':'Es un fichero ejecutable que contiene varios tipos de virus  en su interior.'},
{'term':'Economía Clandestina','definition':'La economía clandestina en línea es el mercado digital donde se compran y se venden bienes y servicios obtenidos a través de la ciberdelincuencia, con el fin de cometer delitos informáticos.'},
{'term':'Encriptación','definition':'Es el proceso para volver ilegible información considera importante. La información una vez encriptada sólo puede leerse aplicándole una clave.'},
{'term':'Exploit','definition':'Un error en el software que representa una brecha de seguridad.'},
{'term':'Extorsión','definition':'El uso de Internet para amenazar con la intención de extorsionar a un individuo para conseguir  dinero u otra cosa de valor.'},
{'term':'Extensión','definition':'Los ficheros se representan asignándoles un nombre y una extensión, separados entre sí por un punto: NOMBRE.EXTENSIÓN.'},
{'term':'Filtración de datos','definition':'Divulgaciones que no están autorizadas  que tratan de adquirir información confidencial y que pueden dar lugar a robos o fugas.'},
{'term':'Firewall','definition':'Un componente de hardware o software diseñado para bloquear el acceso no autorizado.'},
{'term':'Firma de Antivirus','definition':'Las bases de firmas de un antivirus son el conjunto de cadenas que posee para detectar distintos códigos maliciosos. Sus actualizaciones se producen cuando el producto descarga nuevas firmas, que son incorporadas a su base para así poder detectar más amenazas.'},
{'term':'Freeware','definition':'Salida no controlada  de información que hace que esta llegue a personas no autorizadas.'},
{'term':'Freeware','definition':'Es todo aquel software, legalmente distribuido, de forma gratuita.'},
{'term':'Gateway','definition':'Es un ordenador que permite las comunicaciones entre distintos tipos de plataformas, redes, ordenadores o programas.'},
{'term':'Greylisting o Lista Gris','definition':'Una lista gris o greylist es una técnica para el control de mensajes spam. Es un método de defensa que bloquea la mayoría de los spam que se reciben en un servidor de correo.'},
{'term':'Gusanos','definition':'Son programas que realizan copias de sí mismos, alojándolas en diferentes ubicaciones del ordenador. El objetivo de este malware suele ser colapsar los ordenadores y las redes informáticas, impidiendo así el trabajo a los usuarios.'},
{'term':'Hacker','definition':'Persona experta en tecnología dedicada a intervenir y /o realizar alteraciones técnicas con buenas o malas intenciones.'},
{'term':'Hacking','definition':'Acceder de forma ilegal a datos almacenados en un ordenador o servidor.'},
{'term':'Hacktivismo','definition':'Es la función del Hacking y el activismo, la política y la tecnología.'},
{'term':'Hardware','definition':'Término que hace referencia a cada uno de los elementos físicos de un sistema informático (pantalla, teclado, ratón, memoria, disco duro, otros)'},
{'term':'HTTP (HyperText Transfer Protocol','definition':'Es un sistema de comunicación que permite la visualización de páginas Web, desde un navegador.'},
{'term':'Ingeniería Social','definition':'Término que  hace referencia al arte de manipular personas para eludir los sistemas de seguridad. Esta técnica consiste en obtener información de los usuarios por teléfono, correo electrónico, correo tradicional o contacto directo.'},
{'term':'Incidente Informático','definition':'Es la violación o amenaza que afectan la confidencialidad, disponibilidad y la integración como la continuidad de los servicios que son ofrecidos.'},
{'term':'Inyección de código SQL','definition':'Técnica donde el atacante crea o altera comandos SQL, para exponer datos ocultos, sobreescribir los valiosos, o ejecutar comandos peligrosos en un equipo que hospeda bases de datos.'},
{'term':'Índice de peligrosidad','definition':'Es un valor calculado que permite medir lo peligroso que puede llegar a ser un virus.'},
{'term':'Infección','definition':'Es la acción que realizan los virus virus, consistente en introducirse en el ordenador o en áreas concretas de éste y en determinados ficheros.'},
{'term':'IP (Internet Protocol) / TCP-IP','definition':'La IP es la dirección o código que identifica exclusivamente a cada uno de los ordenadores existentes.'},
{'term':'Keylogger','definition':'Es un tipo de malware diseñado para capturar las pulsaciones, movimientos y clics del teclado y del ratón, generalmente de forma encubierta, para intentar robar información personal, como las cuentas y contraseñas de las tarjetas de crédito.'},
{'term':'Lista Blanca','definition':'Método utilizado normalmente por programas de bloqueo de spam, que permite a los correos electrónicos de direcciones de correo electrónicos o nombres de dominio autorizados o conocidos pasar por el software de seguridad.'},
{'term':'Malware','definition':'Término que engloba a todo tipo de programa o código informático malicioso cuya función es dañar un sistema o causar un mal funcionamiento. Dentro de este grupo podemos encontrar términos como: Virus, Troyanos, Gusanos, keyloggers, Botnets,  Ransomware, Spyware, Adware, Hijackers, Keyloggers, FakeAVs, Rootkits, Bootkits, Rogues.'},
{'term':'Mecanismo de Propagación','definition':'Un mecanismo de propagación es el método que utiliza una amenaza para infectar un sistema.'},
{'term':'Mutex','definition':'Técnica utilizada por algunos virus para controlar el acceso a recursos ( programas  u otros virus) y evitar que más de un proceso utilice el mismo recurso al mismo tiempo.'},
{'term':'Negación de servicio (DoS)','definition':'Es un ataque a un sistema de computadoras o red que causa que un servicio o recurso sea inaccesible a los usuarios legítimos.'},
{'term':'Nivel de Propagación','definition':'Se trata de un valor que indica cómo de rápido se puede extender o se ha extendido el virus por todo el mundo. Es usado para mirar la peligrosidad del mismo.'},
{'term':'Nuke (ataque)','definition':'Caída o pérdida de la conexión de red, provocada de forma intencionada por alguna persona. El ordenador sobre el que se realiza un nuke, además puede quedar bloqueado.'},
{'term':'Parches','definition':'Programa que se encarga de hacer cambios en busca de la corrección de vulnerabilidades de seguridad.'},
{'term':'Pharming','definition':'Redirigir el tráfico a un sitio web falso para capturar información confidencial de los usuarios.'},
{'term':'Phishing','definition':'Técnica utilizada por los delincuentes para obtener información confidencial como nombres de usuario, contraseñas y detalles de tarjetas de crédito haciéndose pasar por una comunicación confiable y legítima.'},
{'term':'Piratería','definition':'Infringir los derechos de autor para obtener ganancias financieras o distribuir sin permiso un trabajo que se está preparado para su distribución comercial.'},
{'term':'Programa malicioso','definition':'Tambien conocidos como malware que contienen virus, spyware y otros programas indeseados que se instalan sin consentimiento.'},
{'term':'Protección Heurística','definition':'En el contexto de la protección antivirus, la heurística se compone de un conjunto de reglas que se emplean para detectar el comportamiento de los programas maliciosos sin necesidad de identificar de forma exclusiva a la amenaza específica, como es requerida por la detección clásica basada en firmas.'},
{'term':'Redes punto a punto','definition':'son aquellas que responden a un tipo de arquitectura de red  en las que cada canal de datos se usa para comunicar únicamente dos nodos. Las redes puntos a punto son utilizadas para compartir música, películas, juegos y otros archivos. Sin embargo, también son un mecanismo muy común para la distribución de virus, bots, spyware, adware, troyanos, rootkits, gusanos y otro tipo de malware.'},
{'term':'Ransomware','definition':'Programa maligno que bloquea totalmente nuestro equipo y pide dinero a cambio de devolver el control.'},
{'term':'Riesgo','definition':'Es la posibilidad de que una amenaza se produzca, dando lugar a un ataque.'},
{'term':'Robo de datos','definition':'Los robos de datos pueden producirse tanto dentro de la empresa (por ejemplo, a manos de un trabajador descontento) como mediante ataques de delincuentes desde el exterior.'},
{'term':'Rootkits','definition':'Es un juego de herramientas (programas) que permiten acceder a los niveles administrativos de un ordenador o una red.'},
{'term':'Scareware','definition':'Hacer creer a los usuarios que el equipo está infectado, para hacer comprar una aplicación falsa.'},
{'term':'Sistema de detección de intrusos (IDS)','definition':'Hace referencia a un mecanismo que, sigilosamente, escucha el tráfico en la red para detectar actividades anormales o sospechosas, y de este modo, reducir el riesgo de intrusión.'},
{'term':'Sistema de prevención de intrusiones (IPS):','definition':'Encargados de detectar y bloquear cualquier intento de intrusión, transmisión de código maliciosos, o amenazas a través de la red.'},
{'term':'Software de seguridad fraudulento (rogue)','definition':'Falsos programas de seguridad que no son realmente lo que dicen ser, sino que todo lo contrario. Bajo la promesa de solucionar falsas infecciones, cuando el usuario instala estos programas, su sistema es infectado.'},
{'term':'Spam','definition':'También conocido como correo basura, el spam es correo electrónico que involucra mensajes casi idénticos enviados a numerosos destinatarios.'},
{'term':'Spear phishing','definition':'Estafa por correo electrónico cuyo objetivo es acceso no autorizado a datos, se centra en organizaciones en busca de: robo de propiedad intelectual, datos financieros, secretos comerciales, otros.'},
{'term':'Spyware','definition':'Paquete de software que realiza un seguimiento y envía información de identificación personal o información confidencial a otras personas sin permiso de los usuarios'},
{'term':'Toolkit','definition':'Son programas de software que pueden usarse tanto por novatos como por expertos para facilitar el lanzamiento y distribución de ataques a computadoras en red.'},
{'term':'Tracware','definition':'Es todo programa que realiza el seguimiento de las acciones que realiza el usuario mientras navega por Internet (páginas visitadas, banners que pulsa, etc.) y crea un perfil que utiliza con fines publicitarios.'},
{'term':'Variante','definition':'Es una versión modificada de un virus original, que puede infectar de forma similar o distinta y realizar las mismas acciones u otras.'},
{'term':'Vector de ataque','definition':'Un vector de ataque es el método que utiliza una amenaza para atacar un sistema.'},
{'term':'Virus','definition':'Programa de ordenador capaz de incrustarse en disco y replicarse repetidamente, sin el conocimiento o permiso del usuario.'}]
